-- Drop existing tables if they exist
DROP TABLE IF EXISTS bank_accounts;
DROP TABLE IF EXISTS account_requests;

-- Create `bank_accounts` table
CREATE TABLE bank_accounts (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    account_number VARCHAR(12) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    account_type ENUM('SAVINGS', 'CHECKING') NOT NULL,
    status ENUM('ACTIVE', 'SUSPENDED', 'CLOSED') NOT NULL,
    balance DOUBLE NOT NULL DEFAULT 0.0,
    currency VARCHAR(3) NOT NULL DEFAULT 'USD',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);

-- Create `account_requests` table
CREATE TABLE account_requests (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    account_type ENUM('SAVINGS', 'CHECKING') NOT NULL,
    request_type ENUM('NEW_BANK_ACCOUNT', 'CLOSE_BANK_ACCOUNT', 'SUSPEND_BANK_ACCOUNT') NOT NULL,
    bank_account_id BIGINT DEFAULT NULL,
    status ENUM('PENDING', 'APPROVED', 'REJECTED') NOT NULL DEFAULT 'PENDING',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);
