DROP TABLE IF EXISTS payments;

CREATE TABLE payments (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    bank_account_id BIGINT NOT NULL,
    amount DOUBLE NOT NULL CHECK (amount > 0),
    payment_type ENUM('BILL_PAYMENT', 'EXTERNAL_TRANSFER', 'PAYMENT') NOT NULL,
    receiver_details VARCHAR(255) NOT NULL,
    receiver_bank_account VARCHAR(50) DEFAULT NULL,
    receiver_bank_name VARCHAR(100) DEFAULT NULL,
    status ENUM('PENDING', 'PROCESSED', 'FAILED', 'CANCELED') NOT NULL DEFAULT 'PENDING',
    payment_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


DROP TABLE IF EXISTS scheduled_payments;

CREATE TABLE scheduled_payments (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    bank_account_id BIGINT NOT NULL,
    amount DOUBLE NOT NULL CHECK (amount > 0),
    payment_type ENUM('BILL_PAYMENT', 'EXTERNAL_TRANSFER', 'PAYMENT') NOT NULL,
    receiver_details VARCHAR(255) NOT NULL,
    receiver_bank_account VARCHAR(50) DEFAULT NULL,
    receiver_bank_name VARCHAR(100) DEFAULT NULL,
    status ENUM('PENDING', 'CANCELED') NOT NULL DEFAULT 'PENDING',
    payment_date DATETIME NOT NULL,
    recurring_type ENUM('NONE', 'DAILY', 'WEEKLY', 'MONTHLY') DEFAULT 'NONE',
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
